### ISSUE TITLE
training-operator is blocked when deployed as part Kubeflow bundle 1.6/stable

### ISSUE THREAD

**Issue by i-chvets** [canonical/training-operator#74]
When deploying Kubeflow bundle using `1.6/stable` (`juju deploy kubeflow --trust --channel 1.6/stable`), `training-operator` component is stuck in `blocked` state reporting failure to create K8S resources. Removing and redeploying result in the same issue.
```
training-operator                                     waiting          1  training-operator        1.5/stable       65  10.152.183.125  no       installing agent
training-operator/0*          blocked      idle       10.1.234.79                     Patching resources failed with code 404.
```
Related logs:
```
lightkube.core.exceptions.ApiError: customresourcedefinitions.apiextensions.k8s.io "mpijobs.kubeflow.org" not found
```

Complete Juju debug log:
https://pastebin.canonical.com/p/m6rbzmQfCK/

**Comment by DnPlas** [comment]
Thanks for reporting this @i-chvets. I am not able to reproduce the issue, but I see some `SIGTERM` messages in your `juju debug-log` before the error message with the mpi `CRD` appears:

`unit-training-operator-0: 15:31:08 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: signal: terminated`

This makes me think that something in the cluster happened while the install event handler was working on creating the k8s resources, then when config-changed fired and it tried to patch the mpi CRD, it could not due to it not being present in the cluster.
May I ask if you noticed some interruption (maybe microk8s stopped?) in the early stages of deploying the bundle?

**Comment by i-chvets** [comment]
Most likely this was due to bad cluster state when install was tested.
This issue can be closed now.
